import Foundation

class ProjectStore: ObservableObject {
    private let key = "com.provenance.projects"
    @Published private(set) var projects: [Project] = []

    init() { load() }

    // MARK: - CRUD

    /// Adds a project, guarding against duplicate projectIds (section 9).
    ///
    /// If a project with the same `projectId` but different `id` already exists
    /// (e.g. folder was moved and reconnected), update its location instead of
    /// creating a second entry.
    func add(_ project: Project) {
        // Duplicate-projectId guard — authoritative location wins
        if let idx = projects.firstIndex(where: {
            $0.projectId == project.projectId && $0.id != project.id
        }) {
            projects[idx].folderURL      = project.folderURL
            projects[idx].folderBookmark = project.folderBookmark
            save()
            return
        }
        projects.append(project)
        save()
    }

    func remove(id: UUID) {
        projects.removeAll { $0.id == id }
        save()
    }

    func update(_ project: Project) {
        if let idx = projects.firstIndex(where: { $0.id == project.id }) {
            projects[idx] = project
            save()
        }
    }

    // MARK: - Persistence

    private func load() {
        guard let data = UserDefaults.standard.data(forKey: key) else { return }
        projects = (try? JSONDecoder().decode([Project].self, from: data)) ?? []
        migrateLegacyFields()
        deduplicateIfNeeded()
    }

    /// PR-10 migration: create NSURL bookmarks for any project that lacks one,
    /// and persist any projectIds that were freshly generated by the custom
    /// Project.init(from:) for pre-PR-10 store entries. Runs on first launch
    /// after PR-10; subsequent launches are no-ops (existing values are unchanged).
    func migrateLegacyFields() {
        var dirty = false
        for i in projects.indices {
            if projects[i].folderBookmark == nil {
                if let bm = try? projects[i].folderURL.bookmarkData(
                    options: .withSecurityScope,
                    includingResourceValuesForKeys: nil,
                    relativeTo: nil
                ) {
                    projects[i].folderBookmark = bm
                    dirty = true
                }
            }
        }
        // Always save when projects exist: this persists any projectIds that were
        // freshly generated by Project.init(from:) for pre-PR-10 store entries,
        // ensuring stability across subsequent launches.
        if !projects.isEmpty { dirty = true }
        if dirty { save() }
    }

    // MARK: - Deduplication (PR-11)

    /// Groups projects by `projectId`. When multiple entries share the same ID
    /// (e.g. iCloud sync showing the same folder under two paths), keep the best
    /// one and discard the rest from the in-memory + persistent store.
    ///
    /// "Discard" means removed from the store array — it does NOT delete any
    /// `.ledger/` directory on disk.
    ///
    /// Logs a single `projectsDeduplicated` ledger event per group that needed
    /// cleaning. Idempotent; no-op when there are no duplicates.
    private func deduplicateIfNeeded() {
        // Group indices by projectId
        var byId: [String: [Int]] = [:]
        for (i, p) in projects.enumerated() {
            byId[p.projectId, default: []].append(i)
        }

        var indicesToRemove: [Int] = []

        for (projectId, indices) in byId where indices.count > 1 {
            let group = indices.map { projects[$0] }
            let best  = pickBest(from: group)
            let discardedCount = group.count - 1

            // Collect indices of all entries that are NOT the best one
            for idx in indices where projects[idx].id != best.id {
                indicesToRemove.append(idx)
            }

            // Log one event on the kept project's ledger
            LedgerWriter.appendEvent(
                type: .projectsDeduplicated,
                detail: "Removed \(discardedCount) duplicate project \(discardedCount == 1 ? "entry" : "entries") (kept projectId \(projectId)).",
                to: best
            )
        }

        guard !indicesToRemove.isEmpty else { return }

        let removeSet = Set(indicesToRemove)
        projects = projects.enumerated()
            .filter { !removeSet.contains($0.offset) }
            .map(\.element)
        save()
    }

    /// Picks the best project from a duplicate group.
    ///
    /// Priority:
    ///   1. Entries whose folder path currently exists on disk.
    ///   2. Among those (or among all, if none exist), the most recent `lastActivity`.
    private func pickBest(from group: [Project]) -> Project {
        let fm = FileManager.default
        let resolving = group.filter {
            var isDir: ObjCBool = false
            return fm.fileExists(atPath: $0.folderURL.path, isDirectory: &isDir) && isDir.boolValue
        }
        let candidates = resolving.isEmpty ? group : resolving
        return candidates.max(by: { $0.lastActivity < $1.lastActivity }) ?? group[0]
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(projects) else { return }
        UserDefaults.standard.set(data, forKey: key)
    }
}
