import Foundation

class ProjectStore: ObservableObject {
    private let key = "com.provenance.projects"
    @Published private(set) var projects: [Project] = []

    init() { load() }

    // MARK: - CRUD

    /// Adds a project, guarding against duplicate projectIds (section 9).
    ///
    /// If a project with the same `projectId` but different `id` already exists
    /// (e.g. folder was moved and reconnected), update its location instead of
    /// creating a second entry.
    func add(_ project: Project) {
        // Duplicate-projectId guard — authoritative location wins
        if let idx = projects.firstIndex(where: {
            $0.projectId == project.projectId && $0.id != project.id
        }) {
            projects[idx].folderURL      = project.folderURL
            projects[idx].folderBookmark = project.folderBookmark
            save()
            return
        }
        projects.append(project)
        save()
    }

    func remove(id: UUID) {
        projects.removeAll { $0.id == id }
        save()
    }

    func update(_ project: Project) {
        if let idx = projects.firstIndex(where: { $0.id == project.id }) {
            projects[idx] = project
            save()
        }
    }

    // MARK: - Persistence

    private func load() {
        guard let data = UserDefaults.standard.data(forKey: key) else { return }
        projects = (try? JSONDecoder().decode([Project].self, from: data)) ?? []
        migrateLegacyFields()
    }

    /// PR-10 migration: create NSURL bookmarks for any project that lacks one,
    /// and persist any projectIds that were freshly generated by the custom
    /// Project.init(from:) for pre-PR-10 store entries. Runs on first launch
    /// after PR-10; subsequent launches are no-ops (existing values are unchanged).
    func migrateLegacyFields() {
        var dirty = false
        for i in projects.indices {
            if projects[i].folderBookmark == nil {
                if let bm = try? projects[i].folderURL.bookmarkData(
                    options: .withSecurityScope,
                    includingResourceValuesForKeys: nil,
                    relativeTo: nil
                ) {
                    projects[i].folderBookmark = bm
                    dirty = true
                }
            }
        }
        // Always save when projects exist: this persists any projectIds that were
        // freshly generated by Project.init(from:) for pre-PR-10 store entries,
        // ensuring stability across subsequent launches.
        if !projects.isEmpty { dirty = true }
        if dirty { save() }
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(projects) else { return }
        UserDefaults.standard.set(data, forKey: key)
    }
}
